### ISSUE TITLE
Compact PCIAddress list instead of multiple mechanisms.

### ISSUE THREAD

**Issue by haiodo** [networkservicemesh/sdk-sriov#12]
Right now SR-IOV forwarder will copy Kernel, vfio mechanisms with individual PCIAddresses specified, but I think we need a generic solution to pass a list of available PCIAddress list for Endpoint to choose.

**Comment by edwarnicke** [comment]
Could you say more about what you are thinking here?  The Device Plugin part will inject some number of devices, and env variables...

**Comment by Bolodya1997** [comment]
No more needed because endpoint doesn't make any VF selection.

**Comment by denis-tingaikin** [comment]
Closing by https://github.com/networkservicemesh/sdk-sriov/issues/12#issuecomment-762048467
