### ISSUE TITLE
sdk-sriov is not updated to latest sdk-kernel

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk-sriov#196]
## Problem

sdk-kernel has been refactored in https://github.com/networkservicemesh/sdk-kernel/pull/231
and now sdk-kernel is not compatible with sdk-sriov https://github.com/networkservicemesh/sdk-kernel/runs/2858487871

To avoid this issue on releasing we used the latest compatible sdk-kernel version with updated deps to sdk and api: https://github.com/networkservicemesh/sdk-kernel/compare/release/v1.0.0...main

**Comment by denis-tingaikin** [comment]
@edwarnicke should we update sdk-sriov to latest sdk-kernel or we need to revert refactorings in sdk-kernel? Please share your thoughts.

**Comment by denis-tingaikin** [comment]
@edwarnicke as we discussed at PR meeting we'll update sdk-sriov to the latest sdk-kernel and will fix any issues

**Comment by glazychev-art** [comment]
Found the next problem:
When we want to update dependent repositories we do `go get -u github.com/networkservicemesh/sdk-sriov@main`
But `go` downloads wrong version of the packages:
```
Run GOPROXY=direct go get -u github.com/networkservicemesh/sdk-sriov@main
go: downloading github.com/networkservicemesh/sdk-sriov v0.0.0-20210625105718-c4fc34e325ee
go get: upgraded github.com/networkservicemesh/sdk-sriov v0.0.0-20210624061855-55d455bd92bc => v0.0.0-20210625105718-c4fc34e325ee
...
go: downloading github.com/networkservicemesh/api v1.0.0
go: downloading github.com/networkservicemesh/sdk v1.0.0
...
go: downloading github.com/networkservicemesh/sdk-kernel v1.0.1
...
```
We _don't_ need `v1.0.0`, we should use _main_ branch

**Comment by denis-tingaikin** [comment]
What if we'll do
```
go get -u github.com/networkservicemesh/sdk-sriov@main
go get -u github.com/networkservicemesh/sdk@main
go get -u github.com/networkservicemesh/api@main
```
And also interesting will the problem reproducible with:
```
go get -u github.com/networkservicemesh/sdk-sriov@${SHA:7}
```

**Comment by glazychev-art** [comment]
This produces the same result:
`go get -u github.com/networkservicemesh/sdk-sriov@${SHA:7}`

Eventually, this works:
```
go get .../sdk-sriov@main
go get .../sdk@main
go get .../api@main
```
`go get .../sdk@main` - removes unnecessary modules. Maybe we can take this as a workaround.

**Comment by denis-tingaikin** [comment]
ok, cool, then we can use this as a workaround for the issue if we don't get a more smart solution
