### ISSUE TITLE
implement sriov token server chain element

### ISSUE THREAD

**Issue by pperiyasamy** [networkservicemesh/sdk-sriov#246]
The sdk-sriov repo already contains sriov token client chain element which can be used by NSCs to create service request with tokenID to request for VF attachment.
 But there is no server chain element exists so that NSEs can issue available token id via mechanism parameter for every client connection request, this token id can be later used by forwarder to attach a dedicated VF for every client connection. This chain element should be also an idempotent for the existing client connection. When no tokens are present for new client connections, then consider skipping it and execute subsequent chain element.

**Comment by edwarnicke** [comment]
@pperiyasamy Would it make sense here to simply include the token in the Mechanism returned by the NSE?

**Comment by pperiyasamy** [comment]
@edwarnicke just returning token id might work for dedicated VF case (i.e. one VF per client connection). 
In this case, NSE is brought up with required sriov resources upfront based on number of clients it would serve.
The sriov token server element is initialised with allocated token id list, then it would assign a token from the list and send it in mechanism parameter for every client connection request.

I thought storing (via [resource pool client](https://github.com/networkservicemesh/sdk-sriov/blob/main/pkg/networkservice/common/resourcepool/client.go#L88-L95) communicating assigned VF pci address back into NSE with another another service request) and then sending VF pci address  into mechanism parameter might be useful for VLAN sub interface case. 
can we implement this later ?

or you have other thoughts ?
